<?php
$typeArr[1] = '关于我们';
$typeArr[2] = '企业介绍';
$typeArr[3] = '企业环境';
$typeArr[4] = '荣誉资质';
$typeArr[5] = '新闻中心';
$typeArr[6] = '公司动态';
$typeArr[7] = '行业动态';
$typeArr[8] = '网站公告';
$typeArr[9] = '业务范围';
$typeArr[10] = '矿产开发';
$typeArr[11] = '地产';
$typeArr[12] = '电商与互联网';
$typeArr[13] = '旅游度假';
$typeArr[14] = '企业文化';
$typeArr[15] = '企业愿景';
$typeArr[16] = '企业价值';
$typeArr[17] = '企业精神';
$typeArr[18] = '员工风采';
$typeArr[19] = '人才招聘';
$typeArr[20] = '联系我们';
$typeArr[21] = '联系我们';
$typeArr[22] = '公司地图';
$typeArr[23] = '董事长致辞';
?>