<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1001,1036);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n		  <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n		  ",1302,1506);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<li><a class='on' href='~typelink~' ~rel~>~typename~</a></li>";
$z[4]=Array("global","",1841,1864);
$z[4][4]['name']="cfg_yxdh";
$z[5]=Array("global","",2055,2078);
$z[5][4]['name']="cfg_zbdh";
$z[6]=Array("field","",2289,2318);
$z[6][4]['name']="position";
$z[7]=Array("field","",2328,2357);
$z[7][4]['name']="typename";
$z[8]=Array("field","",2468,2487);
$z[8][4]['name']="title";
$z[9]=Array("field","",2537,2589);
$z[9][4]['name']="pubdate";
$z[9][4]['function']="MyDate('Y/m/d',@me)";
$z[10]=Array("field","",2599,2619);
$z[10][4]['name']="writer";
$z[11]=Array("field","",2669,2687);
$z[11][4]['name']="body";
$z[12]=Array("prenext","",2783,2808);
$z[12][4]['get']="pre";
$z[13]=Array("prenext","",2861,2887);
$z[13][4]['get']="next";
$z[14]=Array("include","",3063,3100);
$z[14][4]['filename']="footer.htm";

?>