<?php
$z[0]=Array("channelartlist","\r\n      <li><a class='{dede:field.currentstyle/}' href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n        <div class=\"box\">\r\n          <div class=\"left\">\r\n		  {dede:channel type='son'}\r\n		  <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n		  {/dede:channel}\r\n		  </div>\r\n        </div>\r\n      </li>\r\n	  ",262,665);
$z[0][4]['typeid']="top";
$z[0][4]['currentstyle']="on";

?>