<?php
$z[0]=Array("global","",304,330);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("channelartlist","\r\n      <li><a class='{dede:field.currentstyle/}' href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n        <div class=\"box\">\r\n          <div class=\"left\">\r\n		  {dede:channel type='son'}\r\n		  <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n		  {/dede:channel}\r\n		  </div>\r\n        </div>\r\n      </li>\r\n	  ",1762,2165);
$z[1][4]['typeid']="top";
$z[1][4]['currentstyle']="on";
$z[2]=Array("arclist","\r\n			<li>\r\n              <h3><a href=\"[field:arcurl /]\">[field:title/]</a></h3>\r\n              <p>[field:infos/]…</p>\r\n            </li>\r\n			",2502,2739);
$z[2][4]['row']="2";
$z[2][4]['typeid']="7";
$z[2][4]['titlelen']="60";
$z[2][4]['infolen']="60";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("arclist","\r\n			  <li>\r\n                <div class=\"pic\"><a href=\"[field:arcurl /]\"><img src=\"[field:picname/]\" height=\"50px\" width=\"70px\"></a></div>\r\n                <div class=\"text\">\r\n                  <h3><a href=\"[field:arcurl /]\">[field:title/]</a></h3>\r\n                  <p><a href=\"[field:arcurl /]\">详细&gt;&gt;</a></p>\r\n                </div>\r\n                <div class=\"clear\"></div>\r\n              </li>\r\n			  ",4208,4718);
$z[3][4]['row']="2";
$z[3][4]['typeid']="5";
$z[3][4]['titlelen']="60";
$z[3][4]['infolen']="100";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("include","",5383,5420);
$z[4][4]['filename']="footer.htm";

?>