<?php
$z[0]=Array("channel","\r\n		  <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n		  ",101,305);
$z[0][4]['row']="10";
$z[0][4]['type']="son";
$z[0][4]['col']="1";
$z[0][4]['currentstyle']="<li><a class='on' href='~typelink~' ~rel~>~typename~</a></li>";
$z[1]=Array("global","",640,667);
$z[1][4]['name']="cfg_yingxiao";
$z[2]=Array("global","",858,883);
$z[2][4]['name']="cfg_zongbu";

?>