<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1001,1036);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n		  <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n		  ",1300,1504);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<li><a class='on' href='~typelink~' ~rel~>~typename~</a></li>";
$z[4]=Array("global","",1839,1862);
$z[4][4]['name']="cfg_yxdh";
$z[5]=Array("global","",2053,2076);
$z[5][4]['name']="cfg_zbdh";
$z[6]=Array("field","",2286,2315);
$z[6][4]['name']="position";
$z[7]=Array("field","",2325,2354);
$z[7][4]['name']="typename";
$z[8]=Array("list","\r\n			<li>\r\n              <div class=\"pic\"><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" /></a></div>\r\n              <div class=\"text\">\r\n                <h2><a href=\"[field:arcurl/]\">[field:title/]</a></h2>\r\n                <p>[field:infos/]…<a href=\"[field:arcurl/]\">更多&gt;&gt;</a></p>\r\n              </div>\r\n            </li>\r\n			",2517,2912);
$z[8][4]['pagesize']="5";
$z[8][4]['infolen']="150";
$z[9]=Array("pagelist","",3001,3056);
$z[9][4]['istitem']="index,pre,next,";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",3155,3192);
$z[10][4]['filename']="footer.htm";

?>