<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1001,1036);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n		  <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n		  ",1316,1520);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<li><a class='on' href='~typelink~' ~rel~>~typename~</a></li>";
$z[4]=Array("global","",1855,1878);
$z[4][4]['name']="cfg_yxdh";
$z[5]=Array("global","",2069,2092);
$z[5][4]['name']="cfg_zbdh";
$z[6]=Array("field","",2302,2331);
$z[6][4]['name']="position";
$z[7]=Array("field","",2341,2370);
$z[7][4]['name']="typename";
$z[8]=Array("field","",2471,2492);
$z[8][4]['name']="content";
$z[9]=Array("include","",2585,2622);
$z[9][4]['filename']="footer.htm";

?>