<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1001,1036);
$z[2][4]['filename']="head.htm";
$z[3]=Array("include","",1180,1215);
$z[3][4]['filename']="left.htm";
$z[4]=Array("field","",1289,1318);
$z[4][4]['name']="position";
$z[5]=Array("field","",1328,1357);
$z[5][4]['name']="typename";
$z[6]=Array("global","",1658,1713);
$z[6][4]['name']="keyword";
$z[6][4]['function']="RemoveXSS(@me)";
$z[7]=Array("list","\r\n			<li>\r\n              <div class=\"text\">\r\n                <h2><a href=\"[field:arcurl/]\">[field:title/]</a></h2>\r\n                <p>[field:infos/]…<a href=\"[field:arcurl/]\">更多&gt;&gt;</a></p>\r\n              </div>\r\n            </li>\r\n			",1751,2047);
$z[7][4]['perpage']="20";
$z[7][4]['infolen']="300";
$z[8]=Array("pagelist","",2136,2191);
$z[8][4]['istitem']="index,pre,next,";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",2290,2327);
$z[9][4]['filename']="footer.htm";

?>