<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1001,1036);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n		  <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n		  ",1306,1510);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<li><a class='on' href='~typelink~' ~rel~>~typename~</a></li>";
$z[4]=Array("global","",1845,1868);
$z[4][4]['name']="cfg_yxdh";
$z[5]=Array("global","",2059,2082);
$z[5][4]['name']="cfg_zbdh";
$z[6]=Array("field","",2292,2321);
$z[6][4]['name']="position";
$z[7]=Array("field","",2331,2360);
$z[7][4]['name']="typename";
$z[8]=Array("field","",2461,2482);
$z[8][4]['name']="content";
$z[9]=Array("include","",2575,2612);
$z[9][4]['filename']="footer.htm";

?>